### ISSUE TITLE
`ResetDatabase` trait is incompatible with attributes of `ConfigurableKernelTestCase`

### ISSUE THREAD

**Issue by yariksheptykin** [teamneusta/pimcore-testing-framework#17]
`\Neusta\Pimcore\TestingFramework\Database\ResetDatabase::_resetDatabase` tries to boot Kernel `beforeClass`. This is too early, as attributes for the Kernel dynamic configuration only collected in `@before` in `_getKernelConfigurationFromAttributes`. In my case, this throws errors while booting kernel about unknown `fos_http_cache` extension config:

```
There is no extension able to load the configuration for "fos_http_cache"
```

```php
#[RegisterBundle(FOSHttpCacheBundle::class)]
final class EventSubscriberConfigurationTest extends ConfigurableKernelTestCase
{
    use ProphecyTrait;
    use ResetDatabase;
...
```

**Comment by yariksheptykin** [comment]
A workaround is to register bundles with `bundles.php` in `tests/app/config/bundles.php`

**Comment by yariksheptykin** [comment]
We might need to add `@beforeClass` to ConfigurableKernelTestCase and scan for class attributes for Kernel config in there to handle this. I am not sure though how to make sure this @beforeClass runs prior to the one from ResetDatabase.

**Comment by jdreesen** [comment]
The problem was that the bundle was configured via an attribute, but its configuration was in a normal `config/packages/*.yaml` file which gets loaded every time the kernel is booted.

The solution is to register *both* statically (load the bundle in the kernel or in `config/bundles.php` *and* register its configuration in a `config/packages/*.yaml` file) or load *both* dynamically (via attributes).
